spring:
  data:
    redis:
      host: 192.168.44.130
      port: 6379
      password: 123456
      database: 0
      # springboot默认使用lettuce，如果要使用jedis，需要引入jedis的依赖
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: 1000